// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMMxRkncOtSl1RbdE24KcsLGW9gsNifA',
    appId: '1:272709294863:web:1383dbb42df5f156ad7c7a',
    messagingSenderId: '272709294863',
    projectId: 'app1-d88a4',
    authDomain: 'app1-d88a4.firebaseapp.com',
    storageBucket: 'app1-d88a4.appspot.com',
    measurementId: 'G-ZG8TRV3BEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6n4vdG5FEdh1gb3EAzS-etlEnQJZJk64',
    appId: '1:272709294863:android:ec40b3229f3a396cad7c7a',
    messagingSenderId: '272709294863',
    projectId: 'app1-d88a4',
    storageBucket: 'app1-d88a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_4HP8JPOkL7poYuz8HxQZj8YV3szbbo',
    appId: '1:272709294863:ios:21eb937e1229c017ad7c7a',
    messagingSenderId: '272709294863',
    projectId: 'app1-d88a4',
    storageBucket: 'app1-d88a4.appspot.com',
    iosClientId: '272709294863-i17m05faqono3rjndp9b4ghfgosbr8ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_4HP8JPOkL7poYuz8HxQZj8YV3szbbo',
    appId: '1:272709294863:ios:85a86fdcd356615cad7c7a',
    messagingSenderId: '272709294863',
    projectId: 'app1-d88a4',
    storageBucket: 'app1-d88a4.appspot.com',
    iosClientId: '272709294863-ts3rrjjrlatm80434jhqlps4cr0ce4b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
